accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import signup

urlpatterns = [
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', signup, name='signup'),

]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

# /

urlpatterns = [
    path('admin/', admin.site.urls),
    path('receipts/', include ("receipts.urls")),
    path("",RedirectView.as_view(url=reverse_lazy("home"))),  # reverses to 'home' to other 'home' and to receiptlistview if nothing in the browser bar
    path('accounts/', include('accounts.urls')),

]
# urls tell django what urls to run what views

receipts/urls.py
from django.urls import path
from receipts.views import (ReceiptListView, ReceiptCreateView)

# receipts/
urlpatterns = [
    path('', ReceiptListView.as_view(), name='home'),
    path('create/', ReceiptCreateView.as_view(), name='create_receipt')

]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL

    # The ExpenseCategory model is a value that we can apply to receipts like "gas" or "entertainment".

class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(USER_MODEL, related_name = 'categories', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    # The Account model is the way that we paid for it, such as with a specific credit card or a bank account.

class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)  # update to CharField
    owner = models.ForeignKey(USER_MODEL, related_name = 'accounts', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    # The Receipt model is the primary thing that this application keeps track of for accounting purposes.

class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(decimal_places=3, max_digits=10)
    tax = models.DecimalField(decimal_places=3, max_digits=10)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(USER_MODEL, related_name='receipts', on_delete=models.CASCADE)
    category = models.ForeignKey('ExpenseCategory', related_name='receipts', on_delete=models.CASCADE)
    account = models.ForeignKey('Account', related_name='receipts', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.models import User

# Create your views here.

    # You need to create a function view to handle showing the sign-up form, and handle its submission. This is a view, so you should create it in the file in the accounts directory that should hold the views.

def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)



# def signup(request):
#     if request.method == 'post':
#         # print(request.method)
#         # print(request.post)
#         formvariable = UserCreationForm(request.POST)
#         if formvariable.is_valid():
#             user = formvariable.save
#             login(request, user)
#             return redirect("home")

#     else:
#         formvariable = UserCreationForm()

#     return render(request, 'registration/signup.html', {"form": formvariable})

receipts/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView

from receipts.models import Receipt

class ReceiptListView(LoginRequiredMixin, ListView):
    model=Receipt
    template_name="receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)

        # Change the queryset of the view to filter the Receipt objects where purchaser equals the logged in user.

class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name="receipts/create.html"
    fields=['vendor', 'total', 'tax', 'date','category', 'account']

# removed 'date' from fields above

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        form.save_m2m
        return redirect('home')

        # Setting the user
        # If you are using class views, you can set the user by writing your own form_valid method. The general form of a method that assigns the current user to a User property looks like this.

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Document</title>
    </head>
    <body>
        <header>
            <nav>
              <ul class="navigation">
                {% if user.is_authenticated %}
                <li class="nav-item">
                  <a href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                  <a href="{% url 'signup' %}">Sign Up</a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'login' %}">Login</a>
                </li>
                {% endif %}
              </ul>
            </nav>
          </header>
        {% block content %}
        {% endblock content %}
    </body>
</html>

receipts/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">


        <title>Document</title>
    </head>
    <body>
        {% block content %}
        {% endblock content %}
    </body>
</html>

receipts/templates/receipts/create.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div>
            <h1>Create Receipt</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <h1>My Receipts</h1>
            <table>
                <thead>
                    <tr>
                    <th>Vendor</th>
                    <th>Total</th>
                    <th>Tax</th>
                    <th>Date</th>
                    <th>Category</th>
                    <th>Account</th>
                    </tr>
                </thead>
                <tbody>
                    {% for receipt in receipt_list %}
                    <tr>
                        <td>{{ receipt.vendor }}</td>
                        <td>{{ receipt.total }}</td>
                        <td>{{ receipt.tax }}</td>
                        <td>{{ receipt.date|date:"m/d/Y" }}</td>
                        <td>{{ receipt.category.name }}</td>
                        <td>{{ receipt.account.name }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
    </main>
    {% endblock content %}